### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Mr-DavyJones** [cosmic-cortex/neural-networks-from-scratch#2]
Hey @cosmic-cortex , 
I am creating a Deep Learning lesson for university students at the moment and stumbled across your repo. I really like the approach of implementing things from the bottom up in numpy, so I am curious if I could use some of your work?
As you don't have a license in this repo at the moment.

Thank you.

**Comment by cosmic-cortex** [comment]
Hi!

Sure, I am honored! For some reason, I forgot to add one, but I have added the MIT license now. So, you are free to use, modify, distribute, etc.
